name: Ellisbeetle Entertainment
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Ellisbeetle Entertainment LLC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fef9f3'
    - '#ccbaba'
    - '#060e10'
    - '#d40000'
    - '#5e5862'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
