name: Ellisbeetle
favicon: null
layout_spectrum: 0.73821
typography_spectrum: 0.92788
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000105'
    - '#e4e0e1'
    - '#00447f'
    - '#cd0000'
    - '#fe7500'
  brandStrength: 0.33094432298094034
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
