name: Ellisbeetle
favicon: null
layout_spectrum: 0.7729846693109721
typography_spectrum: 0.92659
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ededdc'
    - '#000000'
    - '#252018'
    - '#5e5b52'
    - '#9f9c90'
  brandStrength: 0.33094432298094034
  lightness: 0.38119369628839195
  saturation: 0.39093290152959526
  rhythmicContrast: 0.5733864977955818
purpose: []
