name: Ellisbeetle Entertainment LLC
favicon: null
layout_spectrum: 0.35099
typography_spectrum: 1
title: ellisbeetle.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#272727'
    - '#adadad'
    - '#6f6f6f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
