name: Ellisbeetle Entertainment LLC
favicon: null
layout_spectrum: 0.24864
typography_spectrum: 1
title: ellisbeetle.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e9ee'
    - '#0a2d4b'
    - '#9ab5c6'
    - '#758b9c'
    - '#446c86'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
