name: Ellisbeetle Entertainment LLC
favicon: null
layout_spectrum: 0.57375
typography_spectrum: 1
title: Ellisbeetle Entertainment LLC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#322918'
    - '#b0bfac'
    - '#92899a'
    - '#c08d4e'
    - '#875f24'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
