name: Ellisbeetle Entertainment LLC
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Ellisbeetle Entertainment LLC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0a'
    - '#ffffff'
    - '#b6b6b6'
    - '#585857'
    - '#103914'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
