name: Ellisbeetle Entertainment
favicon: null
layout_spectrum: 0.2324
typography_spectrum: 0.92788
title: Ellisbeetle Entertainment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1e1e'
    - '#696969'
    - '#b5b5b5'
    - '#d6d6d6'
    - '#000000'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
