typography_spectrum: 0.07534076902084053
color:
  brandColors:
    - '#FEF9F3'
    - '#070F12'
    - '#C10000'
    - '#FDD600'
    - '#3B91C0'
  brandStrength: 0.40248944819904864
  lightness: 0.8239396251738071
  saturation: 0.5475856522098184
  rhythmicContrast: 0.03826669021509588
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4225293172057718
analytics:
  google: null
  facebook: null
  twitter: null
name: Ellisbeetle Entertainment LLC
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: 798e3bd8-56b6-4bc2-b336-8907485c73b7
    type: content
favicon: null
title: ellisbeetle.com
purpose: []
