typography_spectrum: 1
color:
  brandColors:
    - '#e0e9ee'
    - '#0a2d4b'
    - '#9ab5c6'
    - '#758b9c'
    - '#446c86'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24864
analytics:
  google: null
  facebook: null
  twitter: null
name: Ellisbeetle Entertainment LLC
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: 798e3bd8-56b6-4bc2-b336-8907485c73b7
    type: content
  - name: About
    url: 'http://ellisbeetle.com/about'
    type: external
  - name: Dik and Sak
    id: 15757d29-a9cc-4318-ac10-8ef9055cf826
    type: content
  - name: Cerukins
    id: cd35c0f7-cb90-4a0a-9f6c-eec41be1c181
    type: content
  - name: Ceruladons
    id: cd188ca9-06cb-4a08-b21b-8a65eeff4958
    type: content
favicon: null
title: ellisbeetle.com
purpose: []
